language: c

compiler: gcc

sudo: false

before_install:
  - pip install --user codecov

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_COVERAGE=ON ..

script: cmake --build . && ctest -V .

after_success:
  - gcov CMakeFiles/parg.dir/parg.c.gcno -o CMakeFiles/parg.dir
  - codecov -X gcov
